package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "ras")
public class Compra implements java.io.Serializable {

	private Integer idCompra;
	private Proveedor proveedor;
	private Date fecha;
	private BigDecimal total;
	private boolean vigencia;
	private Set<Logconsulta> logconsultas = new HashSet<Logconsulta>(0);
	private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

	public Compra() {
	}

	public Compra(Proveedor proveedor, boolean vigencia) {
		this.proveedor = proveedor;
		this.vigencia = vigencia;
	}

	public Compra(Proveedor proveedor, Date fecha, BigDecimal total,
			boolean vigencia, Set<Logconsulta> logconsultas,
			Set<Detallecompra> detallecompras) {
		this.proveedor = proveedor;
		this.fecha = fecha;
		this.total = total;
		this.vigencia = vigencia;
		this.logconsultas = logconsultas;
		this.detallecompras = detallecompras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCompra", unique = true, nullable = false)
	public Integer getIdCompra() {
		return this.idCompra;
	}

	public void setIdCompra(Integer idCompra) {
		this.idCompra = idCompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Proveedor_idProveedor", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Total", precision = 10)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "Vigencia", nullable = false)
	public boolean isVigencia() {
		return this.vigencia;
	}

	public void setVigencia(boolean vigencia) {
		this.vigencia = vigencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compra")
	public Set<Logconsulta> getLogconsultas() {
		return this.logconsultas;
	}

	public void setLogconsultas(Set<Logconsulta> logconsultas) {
		this.logconsultas = logconsultas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compra")
	public Set<Detallecompra> getDetallecompras() {
		return this.detallecompras;
	}

	public void setDetallecompras(Set<Detallecompra> detallecompras) {
		this.detallecompras = detallecompras;
	}

}
