package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name = "Distrito", catalog = "ras")
public class Distrito implements java.io.Serializable {

	private Integer idDistrito;
	private String distrito;
	private boolean vigencia;
	private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

	public Distrito() {
	}

	public Distrito(boolean vigencia) {
		this.vigencia = vigencia;
	}

	public Distrito(String distrito, boolean vigencia, Set<Proveedor> proveedors) {
		this.distrito = distrito;
		this.vigencia = vigencia;
		this.proveedors = proveedors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDistrito", unique = true, nullable = false)
	public Integer getIdDistrito() {
		return this.idDistrito;
	}

	public void setIdDistrito(Integer idDistrito) {
		this.idDistrito = idDistrito;
	}

	@Column(name = "Distrito", length = 45)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "Vigencia", nullable = false)
	public boolean isVigencia() {
		return this.vigencia;
	}

	public void setVigencia(boolean vigencia) {
		this.vigencia = vigencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distrito")
	public Set<Proveedor> getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set<Proveedor> proveedors) {
		this.proveedors = proveedors;
	}

}
