package org.ruqu.ras.domain;

// Generated 08-dic-2013 17:26:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EquipoasignadoId generated by hbm2java
 */
@Embeddable
public class EquipoasignadoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int equipoIdEquipo;
	private int proyectoIdProyecto;

	public EquipoasignadoId() {
	}

	public EquipoasignadoId(int equipoIdEquipo, int proyectoIdProyecto) {
		this.equipoIdEquipo = equipoIdEquipo;
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	@Column(name = "Equipo_idEquipo", nullable = false)
	public int getEquipoIdEquipo() {
		return this.equipoIdEquipo;
	}

	public void setEquipoIdEquipo(int equipoIdEquipo) {
		this.equipoIdEquipo = equipoIdEquipo;
	}

	@Column(name = "Proyecto_idProyecto", nullable = false)
	public int getProyectoIdProyecto() {
		return this.proyectoIdProyecto;
	}

	public void setProyectoIdProyecto(int proyectoIdProyecto) {
		this.proyectoIdProyecto = proyectoIdProyecto;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + equipoIdEquipo;
		result = prime * result + proyectoIdProyecto;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EquipoasignadoId other = (EquipoasignadoId) obj;
		if (equipoIdEquipo != other.equipoIdEquipo)
			return false;
		if (proyectoIdProyecto != other.proyectoIdProyecto)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return equipoIdEquipo
				+ "-" + proyectoIdProyecto;
	}
	
	

}
