package org.ruqu.ras.domain;

// Generated 08-dic-2013 17:26:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EquipoasignadoId generated by hbm2java
 */
@Embeddable
public class EquipoasignadoId implements java.io.Serializable {

	private int equipoIdEquipo;
	private int proyectoIdProyecto;

	public EquipoasignadoId() {
	}

	public EquipoasignadoId(int equipoIdEquipo, int proyectoIdProyecto) {
		this.equipoIdEquipo = equipoIdEquipo;
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	@Column(name = "Equipo_idEquipo", nullable = false)
	public int getEquipoIdEquipo() {
		return this.equipoIdEquipo;
	}

	public void setEquipoIdEquipo(int equipoIdEquipo) {
		this.equipoIdEquipo = equipoIdEquipo;
	}

	@Column(name = "Proyecto_idProyecto", nullable = false)
	public int getProyectoIdProyecto() {
		return this.proyectoIdProyecto;
	}

	public void setProyectoIdProyecto(int proyectoIdProyecto) {
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EquipoasignadoId))
			return false;
		EquipoasignadoId castOther = (EquipoasignadoId) other;

		return (this.getEquipoIdEquipo() == castOther.getEquipoIdEquipo())
				&& (this.getProyectoIdProyecto() == castOther
						.getProyectoIdProyecto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEquipoIdEquipo();
		result = 37 * result + this.getProyectoIdProyecto();
		return result;
	}

}
