package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logconsulta generated by hbm2java
 */
@Entity
@Table(name = "logconsulta", catalog = "ras")
public class Logconsulta implements java.io.Serializable {

	private Integer idLogConsulta;
	private Compra compra;
	private Usuario usuario;
	private Equipo equipo;
	private Proyecto proyecto;
	private Date fechaConsulta;

	public Logconsulta() {
	}

	public Logconsulta(Compra compra, Usuario usuario, Equipo equipo,
			Proyecto proyecto) {
		this.compra = compra;
		this.usuario = usuario;
		this.equipo = equipo;
		this.proyecto = proyecto;
	}

	public Logconsulta(Compra compra, Usuario usuario, Equipo equipo,
			Proyecto proyecto, Date fechaConsulta) {
		this.compra = compra;
		this.usuario = usuario;
		this.equipo = equipo;
		this.proyecto = proyecto;
		this.fechaConsulta = fechaConsulta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLogConsulta", unique = true, nullable = false)
	public Integer getIdLogConsulta() {
		return this.idLogConsulta;
	}

	public void setIdLogConsulta(Integer idLogConsulta) {
		this.idLogConsulta = idLogConsulta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Compra_idCompra", nullable = false)
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Usuario_idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Equipo_idEquipo", nullable = false)
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Proyecto_idProyecto", nullable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaConsulta", length = 19)
	public Date getFechaConsulta() {
		return this.fechaConsulta;
	}

	public void setFechaConsulta(Date fechaConsulta) {
		this.fechaConsulta = fechaConsulta;
	}

}
