package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "Opcion", catalog = "ras")
public class Opcion implements java.io.Serializable {

    public static final String WELCOME_VIEW = "Inicio";
    private Integer idOpcion;
    private String descripcion;
    private Opcion opcion;
    private String ruta;
    private boolean vigencia;
    private Set<Opcion> opciones = new HashSet<Opcion>(0);
    private Set<Rol> rols = new HashSet<Rol>(0);

    public Opcion() {
    }

    public Opcion(boolean vigencia) {
        this.vigencia = vigencia;
    }

    public Opcion(String descripcion, boolean vigencia, Set<Rol> rols) {
        this.descripcion = descripcion;
        this.vigencia = vigencia;
        this.rols = rols;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idOpcion", unique = true, nullable = false)
    public Integer getIdOpcion() {
        return this.idOpcion;
    }

    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }

    @Column(name = "Descripcion", length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_menu_padre")
    public Opcion getOpcion() {
        return opcion;
    }

    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }

    @Column(name = "Ruta", length = 45)
    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    @Column(name = "Vigencia", nullable = false)
    public boolean isVigencia() {
        return this.vigencia;
    }

    public void setVigencia(boolean vigencia) {
        this.vigencia = vigencia;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "OpcionAsignadas", catalog = "ras", joinColumns = {@JoinColumn(name = "Opcion_idOpcion", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "Rol_idRol", nullable = false, updatable = false)})
    public Set<Rol> getRols() {
        return this.rols;
    }

    public void setRols(Set<Rol> rols) {
        this.rols = rols;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
    public Set<Opcion> getMenus() {
        return this.opciones;
    }

    public void setMenus(Set<Opcion> opciones) {
        this.opciones = opciones;
    }


}
