package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "Opcion", catalog = "ras")
public class Opcion implements java.io.Serializable {

	private Integer idOpcion;
	private String descripcion;
	private boolean vigencia;
	private Set<Rol> rols = new HashSet<Rol>(0);

	public Opcion() {
	}

	public Opcion(boolean vigencia) {
		this.vigencia = vigencia;
	}

	public Opcion(String descripcion, boolean vigencia, Set<Rol> rols) {
		this.descripcion = descripcion;
		this.vigencia = vigencia;
		this.rols = rols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idOpcion", unique = true, nullable = false)
	public Integer getIdOpcion() {
		return this.idOpcion;
	}

	public void setIdOpcion(Integer idOpcion) {
		this.idOpcion = idOpcion;
	}

	@Column(name = "Descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Vigencia", nullable = false)
	public boolean isVigencia() {
		return this.vigencia;
	}

	public void setVigencia(boolean vigencia) {
		this.vigencia = vigencia;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "opcionasignadas", catalog = "ras", joinColumns = { @JoinColumn(name = "Opcion_idOpcion", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Rol_idRol", nullable = false, updatable = false) })
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

}
