package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Otrogasto generated by hbm2java
 */
@Entity
@Table(name = "otrogasto", catalog = "ras")
public class Otrogasto implements java.io.Serializable {

	private Integer idOtroGasto;
	private Proyecto proyecto;
	private String partida;
	private String descripcion;
	private BigDecimal monto;
	private Date registro;
	private boolean vigencia;

	public Otrogasto() {
	}

	public Otrogasto(Proyecto proyecto, boolean vigencia) {
		this.proyecto = proyecto;
		this.vigencia = vigencia;
	}

	public Otrogasto(Proyecto proyecto, String partida, String descripcion,
			BigDecimal monto, Date registro, boolean vigencia) {
		this.proyecto = proyecto;
		this.partida = partida;
		this.descripcion = descripcion;
		this.monto = monto;
		this.registro = registro;
		this.vigencia = vigencia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idOtroGasto", unique = true, nullable = false)
	public Integer getIdOtroGasto() {
		return this.idOtroGasto;
	}

	public void setIdOtroGasto(Integer idOtroGasto) {
		this.idOtroGasto = idOtroGasto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Proyecto_idProyecto", nullable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "Partida", length = 45)
	public String getPartida() {
		return this.partida;
	}

	public void setPartida(String partida) {
		this.partida = partida;
	}

	@Column(name = "Descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Monto", precision = 10)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Registro", length = 10)
	public Date getRegistro() {
		return this.registro;
	}

	public void setRegistro(Date registro) {
		this.registro = registro;
	}

	@Column(name = "Vigencia", nullable = false)
	public boolean isVigencia() {
		return this.vigencia;
	}

	public void setVigencia(boolean vigencia) {
		this.vigencia = vigencia;
	}

}
