package org.ruqu.ras.domain;

// Generated 24/01/2014 11:25:50 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "partida", catalog = "ras")
public class Partida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPartida;
	private String descripcion;
	private boolean vigencia=true;
	private Set<Otrogasto> otrogastos = new HashSet<Otrogasto>(0);

	public Partida() {
	}

	public Partida(String descripcion, boolean vigencia) {
		this.descripcion = descripcion;
		this.vigencia = vigencia;
	}

	public Partida(String descripcion, boolean vigencia,
			Set<Otrogasto> otrogastos) {
		this.descripcion = descripcion;
		this.vigencia = vigencia;
		this.otrogastos = otrogastos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPartida", unique = true, nullable = false)
	public Integer getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(Integer idPartida) {
		this.idPartida = idPartida;
	}

	@Column(name = "Descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Vigencia", nullable = false)
	public boolean isVigencia() {
		return this.vigencia;
	}

	public void setVigencia(boolean vigencia) {
		this.vigencia = vigencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partida")
	public Set<Otrogasto> getOtrogastos() {
		return this.otrogastos;
	}

	public void setOtrogastos(Set<Otrogasto> otrogastos) {
		this.otrogastos = otrogastos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idPartida == null) ? 0 : idPartida.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Partida other = (Partida) obj;
		if (idPartida == null) {
			if (other.idPartida != null)
				return false;
		} else if (!idPartida.equals(other.idPartida))
			return false;
		return true;
	}

}
