package org.ruqu.ras.domain;

// Generated 14-nov-2013 0:10:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalasignadoId generated by hbm2java
 */
@Embeddable
public class PersonalasignadoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int proyectoIdProyecto;
	private int personalIdPersonal;

	public PersonalasignadoId() {
	}

	public PersonalasignadoId(int proyectoIdProyecto, int personalIdPersonal) {
		this.proyectoIdProyecto = proyectoIdProyecto;
		this.personalIdPersonal = personalIdPersonal;
	}

	@Column(name = "Proyecto_idProyecto", nullable = false)
	public int getProyectoIdProyecto() {
		return this.proyectoIdProyecto;
	}

	public void setProyectoIdProyecto(int proyectoIdProyecto) {
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	@Column(name = "Personal_idPersonal", nullable = false)
	public int getPersonalIdPersonal() {
		return this.personalIdPersonal;
	}

	public void setPersonalIdPersonal(int personalIdPersonal) {
		this.personalIdPersonal = personalIdPersonal;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + personalIdPersonal;
		result = prime * result + proyectoIdProyecto;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PersonalasignadoId other = (PersonalasignadoId) obj;
		if (personalIdPersonal != other.personalIdPersonal)
			return false;
		if (proyectoIdProyecto != other.proyectoIdProyecto)
			return false;
		return true;
	}
	
}
