package org.ruqu.ras.domain;

// Generated 24/01/2014 10:46:59 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "ras")
public class Proveedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProveedor;
	private String nombre;
	private String direccion;
	private String telefono;
	private String ruc;
	private String nombreContacto;
	private String emailContacto;
	private Boolean vigencia=true;
	private Set<Compra> compras = new HashSet<Compra>(0);

	public Proveedor() {
	}

	public Proveedor(String nombre, String direccion, String telefono,
			String ruc, String nombreContacto, String emailContacto,
			Boolean vigencia, Set<Compra> compras) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.ruc = ruc;
		this.nombreContacto = nombreContacto;
		this.emailContacto = emailContacto;
		this.vigencia = vigencia;
		this.compras = compras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProveedor", unique = true, nullable = false)
	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "Nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Direccion", length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "Telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "RUC", length = 15)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "NombreContacto", length = 70)
	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	@Column(name = "EmailContacto", length = 70)
	public String getEmailContacto() {
		return this.emailContacto;
	}

	public void setEmailContacto(String emailContacto) {
		this.emailContacto = emailContacto;
	}

	@Column(name = "Vigencia")
	public Boolean getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(Boolean vigencia) {
		this.vigencia = vigencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

	@Override
	public String toString() {
		return Integer.toString(idProveedor);
	}

	@Override
	public int hashCode() {
		return idProveedor.hashCode();
	}
}
